// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzO2t7hWINxxQPLv-9tdCIH_G4nux8sbU',
    appId: '1:994334466566:web:820a8c8987e5cb2a761987',
    messagingSenderId: '994334466566',
    projectId: 'chesshub-d0d64',
    authDomain: 'chesshub-d0d64.firebaseapp.com',
    storageBucket: 'chesshub-d0d64.appspot.com',
    measurementId: 'G-MS4PL95FG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxaRrT4UIyfsV5o3vjKRYwY1ENDvnsyQ',
    appId: '1:994334466566:android:734f158fa6621e39761987',
    messagingSenderId: '994334466566',
    projectId: 'chesshub-d0d64',
    storageBucket: 'chesshub-d0d64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rD-JjGkJ4pDGhfqZeybo6XlH5XMTQNE',
    appId: '1:994334466566:ios:e5be56ab0c495f3d761987',
    messagingSenderId: '994334466566',
    projectId: 'chesshub-d0d64',
    storageBucket: 'chesshub-d0d64.appspot.com',
    iosBundleId: 'com.example.chesshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rD-JjGkJ4pDGhfqZeybo6XlH5XMTQNE',
    appId: '1:994334466566:ios:e5be56ab0c495f3d761987',
    messagingSenderId: '994334466566',
    projectId: 'chesshub-d0d64',
    storageBucket: 'chesshub-d0d64.appspot.com',
    iosBundleId: 'com.example.chesshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzO2t7hWINxxQPLv-9tdCIH_G4nux8sbU',
    appId: '1:994334466566:web:26da8d4d585ad59d761987',
    messagingSenderId: '994334466566',
    projectId: 'chesshub-d0d64',
    authDomain: 'chesshub-d0d64.firebaseapp.com',
    storageBucket: 'chesshub-d0d64.appspot.com',
    measurementId: 'G-NRLC9J17JX',
  );
}
